// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"
	models "golang-e-wallet-rest-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// TransactionRepository is an autogenerated mock type for the TransactionRepository type
type TransactionRepository struct {
	mock.Mock
}

// Capture provides a mock function with given fields: ctx, transaction
func (_m *TransactionRepository) Capture(ctx context.Context, transaction *models.Transaction) (*models.Transaction, error) {
	ret := _m.Called(ctx, transaction)

	var r0 *models.Transaction
	if rf, ok := ret.Get(0).(func(context.Context, *models.Transaction) *models.Transaction); ok {
		r0 = rf(ctx, transaction)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.Transaction) error); ok {
		r1 = rf(ctx, transaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx, walletNumber, offset, limit
func (_m *TransactionRepository) GetAll(ctx context.Context, walletNumber int64, offset int, limit int) ([]models.TransactionsRow, error) {
	ret := _m.Called(ctx, walletNumber, offset, limit)

	var r0 []models.TransactionsRow
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) []models.TransactionsRow); ok {
		r0 = rf(ctx, walletNumber, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.TransactionsRow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64, int, int) error); ok {
		r1 = rf(ctx, walletNumber, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTransactionRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewTransactionRepository creates a new instance of TransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTransactionRepository(t mockConstructorTestingTNewTransactionRepository) *TransactionRepository {
	mock := &TransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
