// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// TransactionController is an autogenerated mock type for the TransactionController type
type TransactionController struct {
	mock.Mock
}

// GetAllTransactions provides a mock function with given fields: ctx
func (_m *TransactionController) GetAllTransactions(ctx *gin.Context) {
	_m.Called(ctx)
}

// TopUp provides a mock function with given fields: ctx
func (_m *TransactionController) TopUp(ctx *gin.Context) {
	_m.Called(ctx)
}

// Transfer provides a mock function with given fields: ctx
func (_m *TransactionController) Transfer(ctx *gin.Context) {
	_m.Called(ctx)
}

type mockConstructorTestingTNewTransactionController interface {
	mock.TestingT
	Cleanup(func())
}

// NewTransactionController creates a new instance of TransactionController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTransactionController(t mockConstructorTestingTNewTransactionController) *TransactionController {
	mock := &TransactionController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
