// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	repositories "golang-e-wallet-rest-api/internal/repositories"

	mock "github.com/stretchr/testify/mock"
)

// TxFn is an autogenerated mock type for the TxFn type
type TxFn struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *TxFn) Execute(_a0 repositories.TxStore) (interface{}, error) {
	ret := _m.Called(_a0)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(repositories.TxStore) interface{}); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(repositories.TxStore) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTxFn interface {
	mock.TestingT
	Cleanup(func())
}

// NewTxFn creates a new instance of TxFn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTxFn(t mockConstructorTestingTNewTxFn) *TxFn {
	mock := &TxFn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
